EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: Test
      Version: "1.20"
      RoleArn: "arn:aws:iam::882956824445:instance-profile/yasaswini-eks"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-05be9f061a6684ea6
        SubnetIds:
          - subnet-00d54dcf1ce5adc0d
          - subnet-07175d26b040c3501
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
        PublicAccessCidrs: [ "1.1.1.2/32" ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "key"
          Value: "val"
